databases:
  - name: leap-erp-db
    databaseName: leap_erp
    user: leap_erp_user
    plan: free

services:
  - type: web
    name: leap-erp
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn erp_leap.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: leap-erp-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_ENV
        value: production
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.0"
